### ISSUE TITLE
Updating Personal Efforts Week 2 : 30.03.2021- 06.04.2021

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/2021SpringGroup11#10]
Do not forget to update your personal efforts on your own wiki page! It's important to keep track of your time. 

- [x] FİKRİ
- [x] ŞULE
- [ ] EGEMEN
- [x] EMİN
- [x] BEKİR
- [x] EREN
- [x] CANBERK
- [x] SELMAN BERK
- [x] MEHMET YASİN

**Comment by hsuleerkul** [comment]
When you update your page please comment on this issue and delete your name from assignees. This issue will be closed when everyone comments.

**Comment by bekirtatar** [comment]
Updated!
