### ISSUE TITLE
Update Meeting Reports Template

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#111]
Meeting Reports Template needs to be updated according to feedbacks from last meeting #109 

https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-Reports-Template

I think we need to add information about if teacher/customer exists at the meeting or not. They may be added to participants part with * like list item instead of checkbox that is used for team members

**Comment by meltemarsl** [comment]
The group photo of the Renaissance was added to the meeting reports template. The template is completed now.
