### ISSUE TITLE
Update Sequence Diagrams

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#121]
Sequence diagrams will be updated according to the given feedback on the customer meeting held on 31.10.2021.
2 sequence diagrams will be updated until 01.11.2021 - 23.59 (tonight) and then send to Suzan Hoca for review.
After getting her feedback, all of them will be updated accordingly until 02.11.2021 - 13.59.

First 4 sequence diagrams - > Bekir
Remaining 4 sequence diagrams -> Meltem

Since the work will be done on Lucidchart which is a collaborative work environment, the team will be able to keep up to date with each other's work.

**Comment by bekirtatar** [comment]
I updated the first 4 diagrams. We can send it to the customer for feedback.

**Comment by meltemarsl** [comment]
I have sent them to Suzan Hoca, and then uploaded the Github Wiki : https://github.com/bounswe/2021SpringGroup11/wiki/Sequence-Diagram .
