### ISSUE TITLE
Create first API

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#125]
First milestone is on 15th. Django API must be created ASAP..
These tasks will be created as subissue.
- [x] #129
- [x] #130
- [x] #132
- [x] #131
- [x] #133
- [x] #134
- [x] #135
- [x] #136
- [x] #128 
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] #145

**Comment by EAltunoglu** [comment]
These tasks will be created as subissue.
- [ ] Login endpoint
- [ ] Authentication Middleware
- [ ] Refresh JWT Token endpoint
- [ ] User model
- [ ] Send email service
- [ ] Search User endpoint
- [ ] Edit User endpoint

**Comment by EAltunoglu** [comment]
All subissues will be implemented in #125 branch https://github.com/bounswe/2021SpringGroup11/tree/125

**Comment by SelmanB** [comment]
All endpoints are created and tested. Minor glitches remain for #140 and #145. #125 is already deployed, integrated and then rendered obsolete by #143 and #181. Therefore this issue is closed.
