### ISSUE TITLE
Initialization of Redux and Routes

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#127]
Initialize Redux and Routes for "Log in", "Sign up", "Homepage", and "Profile page"
Deadline: 7.11.2021 - 17.00

- [x] @meltemarsl 
- [x] @emindeniz99 
- [x] @bekirtatar

**Comment by bekirtatar** [comment]
Redux and routes are initialized and fixed now. You can test and comment on them in develop branch.

**Comment by bekirtatar** [comment]
@meltemarsl @emindeniz99

**Comment by meltemarsl** [comment]
I have controlled it and it was working properly.

**Comment by emindeniz99** [comment]
It works 🚀
