### ISSUE TITLE
Updating Personal Efforts Week 3 : 06.04.2021- 13.04.2021

### ISSUE THREAD

**Issue by fihlie** [bounswe/2021SpringGroup11#13]
Do not forget to update your personal efforts on your own wiki page! It's important to keep track of your time. 

- [x] FİKRİ
- [x] ŞULE
- [ ] EGEMEN
- [x] EMİN
- [x] BEKİR
- [x] EREN
- [x] CANBERK
- [x] SELMAN BERK
- [x] MEHMET YASİN

**Comment by SelmanB** [comment]
* Egemen is no longer in the group
* Even ignoring that, the issue is outdated anyway.
