### ISSUE TITLE
Create User model

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#133]

**Comment by EAltunoglu** [comment]
Initial version has been created. Modifications might be needed for Milestone3

**Comment by SelmanB** [comment]
User model is supposed to include a profile photo, as defined in #137, which is by now merged with this and #136.

**Comment by EAltunoglu** [comment]
Can be found at backend->api->common->models.py https://github.com/bounswe/2021SpringGroup11/blob/125/source/backend/api/common/models.py
