### ISSUE TITLE
Search User endpoint

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#135]

**Comment by EAltunoglu** [comment]
Fulltext index must be created for 'username' field. https://docs.mongodb.com/manual/core/index-text/

**Comment by SelmanB** [comment]
It is worth checking the [hint](https://docs.mongodb.com/manual/reference/method/cursor.hint/#mongodb-method-cursor.hint) method from MongoDB index search. It says it is only for `mongosh` but maybe we can utilize it somehow for this and future search endpoints.

**Comment by SelmanB** [comment]
Search user endpoint is tested and found stable irrespective of the user model versions, in all branches #125, #143, #181.
