### ISSUE TITLE
Edit User endpoint

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#136]

**Comment by SelmanB** [comment]
#137 is closed and editing user will implement setting a profile photo. It will be another parameter like the other fields. Photo file will be sent as a BASE64.

**Comment by SelmanB** [comment]
See this [resource](https://stackoverflow.com/questions/10827812/what-is-the-length-maximum-for-a-string-data-type-in-mongodb-used-with-ruby) for limitations regarding user photo size in the model.

**Comment by SelmanB** [comment]
The endpoint is tested and found stable in all branches #125, #143, #181.
