### ISSUE TITLE
Delete User endpoint

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#139]

**Comment by SelmanB** [comment]
[this commit](https://github.com/bounswe/2021SpringGroup11/commit/cb05ae83609b8db3623bbb621fffd692919ed635) and [this commit](https://github.com/bounswe/2021SpringGroup11/commit/cbf47af54a6aec55de2b31f42847204dfea22cbf) solve it completely. 

Previously, this functionality was accomplished using `edit-user` endpoint, that possibility is preserved.

**Comment by SelmanB** [comment]
Track the PR in #183
