### ISSUE TITLE
API endpoint definitions

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#141]
Share the documentation with frontend and mobile teams.

**Comment by SelmanB** [comment]
[This Page](https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions) can be used for this purpose.

**Comment by SelmanB** [comment]
[The Page](https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions) is up-to-date and stable but is open for further improvement.

Efficient use of the page is demonstrated by other teams, according to the feedback we received.

**Comment by SelmanB** [comment]
More endpoints and examples will be coming, so this issue is still not closed.

**Comment by EAltunoglu** [comment]
for Milestone 3, definitions are completed.
