### ISSUE TITLE
Code backend API unit tests

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#142]
- [x] #339
- [x] #316
- [x] #340
- [x] #341

**Comment by SelmanB** [comment]
[Postman](https://www.postman.com/) tests are in place and widely used but not pushed to the repo. Shall we export them and push?

**Comment by EAltunoglu** [comment]
To run unit tests:

1. pip install coverage
2. coverage run --source='.' manage.py test

**Comment by SelmanB** [comment]
This issue should not be closed before all the unit test implementations for functionalities listed in #319 are completed.
