### ISSUE TITLE
Discuss password hashing algorithm

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#144]
We are currently using SHA1. We possibly change it to SHA256.

**Comment by SelmanB** [comment]
SHA1 is compromised as explained in [this link](https://auth0.com/blog/sha-1-collision-attack/), even though attacks to access accounts are not really feasible. It might be preferrable to change it to [SHA256](https://en.wikipedia.org/wiki/SHA-2) or [SHA3](https://en.wikipedia.org/wiki/SHA-3)

**Comment by SelmanB** [comment]
Due to infeasibility of such attacks in practice, current algorithm is going to be kept. In the meanwhile, issue will remain open.

**Comment by EAltunoglu** [comment]
This is issue will be closed for now. Backend team is supposed to prioritize other issues.
