### ISSUE TITLE
Design of the Web Profile and Web Homepage

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#147]
Web Profile and Homepages will be designed in correlation with the android design team using Figma. 
Design and colors will be chosen to be consistent with other pages of the application.

Deadline: 10.11.2021-17.00

**Comment by meltemarsl** [comment]
The design of the profile page is completed:
![image](https://user-images.githubusercontent.com/44238703/141272855-59844974-70db-4623-9072-b5f79dfabe38.png)

If there is any missing point, please comment. I will fix it immediately

**Comment by bekirtatar** [comment]
![image](https://user-images.githubusercontent.com/56435823/141515405-8ef07226-c028-4e2f-a47a-9ea689b8c628.png)
The design of the home is also completed.

**Comment by bekirtatar** [comment]
> The design of the profile page is completed: ![image](https://user-images.githubusercontent.com/44238703/141272855-59844974-70db-4623-9072-b5f79dfabe38.png)
> 
> If there is any missing point, please comment. I will fix it immediately

The profile photo and the background picture should be smaller. But since there is no technical difficulty with this, I am closing this issue. The size of the photos will be adjusted while implementing the code. @emindeniz99
