### ISSUE TITLE
Web Profile Page Implementation

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#149]
Profile Page will be implemented and the page will be updated according to the design which will be completed on 10.11.2021-17.00

Deadline: 12.11.2021 - 23.59

**Comment by emindeniz99** [comment]
![image](https://user-images.githubusercontent.com/44745432/141520018-103fef4d-eefa-4e91-8eb3-4203ab0cbc99.png)

**Comment by emindeniz99** [comment]
It is solved with the mentioned pull request. #156 I think it should have been closed automatically.
