### ISSUE TITLE
Web Initial Version of Home Page Implementation

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#151]
Home Page will be implemented according to the design.

Deadline: 12.11.2021 - 23.59

**Comment by meltemarsl** [comment]
Web home page(initial version) is ready:
<img width="943" alt="homee" src="https://user-images.githubusercontent.com/44238703/141961712-93238ce0-e039-44fc-83b6-1bac1bf30cac.png">
