### ISSUE TITLE
Cors Error 

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#177]
![image](https://user-images.githubusercontent.com/57532428/141686693-fd71b084-54eb-4283-9e02-8b27dd7f39c4.png)

**Comment by EAltunoglu** [comment]
[327d052b3ddf54c22e361e56b63045cdbd78e879](https://github.com/bounswe/2021SpringGroup11/commit/327d052b3ddf54c22e361e56b63045cdbd78e879)

**Comment by bekirtatar** [comment]
@EAltunoglu I think you should allow it to all domains. Currently, there is no domain in the ALLOWED_HOSTS variable.
```
ALLOWED_HOSTS=['*']
```

**Comment by bekirtatar** [comment]
It is fixed now.
