### ISSUE TITLE
Creating Deliverables File for Milestone 1 Report

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#193]
Meltem, can you please put together the deliverables that we have worked on, in a .md format so that we can use them easily later forming milestone report. The file should include:
- Requirements UML Software Designs
- Scenarios and Mockups
- Project plan, Communication Plan, RAM
Deadline : 20.11.2021 / 16.00

**Comment by meltemarsl** [comment]
Requirements UML Software Designs, Scenarios and Mockups, and Project Plan, Communication Plan, RAM were added to the group report.
