### ISSUE TITLE
New Milestone Designs on Figma

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#199]
New milestone page designs for android and web will be implemented.

- [x] one path page
- [x] path card

You can edit this comment and add new tasks

**Comment by meltemarsl** [comment]
The resource card design was reviewed and it was decided that the design is sufficient. There is no need to do a new design for it.

**Comment by meltemarsl** [comment]
Path page is designed while implementing, the task is comleted.
