### ISSUE TITLE
Make sure everybody has checked issues

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#2]
This issue will be closed once everybody has answered it acknowledging they have tried and understood github issues feature.

**Comment by hsuleerkul** [comment]
done!

**Comment by emindeniz99** [comment]
done!!

**Comment by bekirtatar** [comment]
I have tried and understood github issues feature.

**Comment by EAltunoglu** [comment]
https://www.youtube.com/watch?v=1ffBJ4sVUb4

**Comment by myasins** [comment]
done

**Comment by canberkboun9** [comment]
done!!!

**Comment by fihlie** [comment]
done!!!!!

**Comment by SelmanB** [comment]
Waiting for @EgemenKaplan before closing :)

**Comment by SelmanB** [comment]
@EgemenKaplan is not part of the group anymore.
