### ISSUE TITLE
Create Issues for Milestone 4 Features

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#202]
All related issues will be created as a sub-issue.

- [x] #203
- [ ] #204
- [x] #206 
- [x] #205
- [x] #227
- [x] #228
- [x] #229
- [x] #230
- [x] #231
- [x] #242
- [x] #243
- [x] #244
- [x] #214
- [x] #215
- [x] #245
- [x] #258
- [x] #259
- [ ] #142 
- [x] #267
- [x] #275
- [x] #279

**Comment by SelmanB** [comment]
All issues are created and the final product for milestone 4 is already released [here](https://github.com/bounswe/2021SpringGroup11/tree/v0.4.0-backend). #204 was already scheduled for the next milestone, and nonfunctional #142 is only partially done for this milestone.
