### ISSUE TITLE
Create a Model for Comment

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#204]
* Comment is another significant model, which provides **_community_** feeling most. It will be implemented thoroughly with the presence of all backend team members.

**Comment by myasins** [comment]
We had added this issue to our plan in case we have much more time than we expected but, we postponed it to our next milestone in order to synchronize with frontend and android teams. Should we keep this issue or close and open a new one after this milestone? @EAltunoglu @SelmanB

**Comment by SelmanB** [comment]
The group decided to remove comment functionality upon discussions with the customer on priorities. Social interaction aspects of the projects will be handled by other means. For more information, see [meeting with customer](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021) and [meeting within group](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-21.1)
