### ISSUE TITLE
Wikidata API Request Research

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#206]
* Since we will use Wikidata requests in some endpoints to satisfy the functionality of our project, it will be useful for backend team to research about it and see some examples.

**Comment by myasins** [comment]
` import requests`
`import json`

`#url = 'https://www.wikidata.org/w/api.php?action=wbsearchentities&search=desert&format=json&errorformat=plaintext&language=en&uselang=en&type=item'`
`#url = 'https://www.wikidata.org/w/api.php?action=wbsearchentities&search=desert&format=json&errorformat=plaintext&language=en&uselang=en&type=item&continue=7'`
`url = 'https://www.wikidata.org/wiki/Special:EntityData/Q2.json'`
`response = requests.get(url)`

`with open('data3.json', 'w+') as outfile:`
   ` json.dump(response.json(), outfile) `

**Comment by myasins** [comment]
Endpoints we will use is tested and a template for this is prepared as I commented above.

**Comment by EAltunoglu** [comment]
The worst documentation I have ever seen.
