### ISSUE TITLE
Wiki Main Page Technology Update

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#208]
The technologies that are used in front-end, back-end and android should be added to the main page of wiki.
Assignee: Meltem
Deadline: 2 December 2021 - 22.00

**Comment by meltemarsl** [comment]
Added to the Github Wiki page as follows:


## Technologies & Languages:

Front-end: VSCode, AWS S3, Redux, Javascript, TypeScript

Back-end: Django, MongoDB, Docker, Google Cloud, Postman, PyCharm, VsCode, Python

Android: Flutter, VSCode(IDE), Android Studio(IDE-Simulation), Dart
