### ISSUE TITLE
Milestone 2 End-Points Review

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#209]
The End-points are discussed in the weekly lab by the members attended. The decided structure of the endpoints will be shared here. This issue will be open until **05.12.2021 midnight** for review and update. When somebody notices a problem or have a feedback over end-points, one should post a comment on this issue. New end-points can be proposed also. 

# LIST:

### Body Arguments
* title: string
* description: string
* photo: Base64 string
* milestones: list of lists of title:string, body:string pairs.
* topics: list of integers corresponding to Wikidata tags

### Response Body
* pathID:int

### URL Arguments
* pathID:int

### Response Body
* title:string
* description:string
* photo:Base64 string
* milestones: list of lists of title:string, body:string pairs.
* topics: list of integers corresponding to Wikidata tags
* creator: string
* reationTime:int (POSIX TS seconds)
* lastUpdated:int (POSIX TS seconds)
* isEnrolled: boolean
* isFav: Boolean

## `POST` `/path/edit-path`
_Same as Create Path_

### URL Arguments
* q:string

### Response Body
* A list of:
		* pathId:int
    * title:string
		* photo:Base64 string
    * effort: int
    * rating: int
    * isEnrolled: boolean
		* isFav: Boolean
    
### URL Arguments
* topic:int (Wikidata tag number)

### Response Body
_Same as Search Path_

### URL Arguments
* q:string

### Response Body
* A list of:
    * ID: int
    * isFav: Boolean
    * name: String

### URL Arguments
* ID:int (Wikidata tag number)

### Response Body
_Same as Search Topic_

* `GET` `/user/related-user`
### URL Arguments
* ID:int (Wikidata tag number)

### Response Body
_Same as Search User_

**Comment by EAltunoglu** [comment]
All endpoints reviewed before Milestone 2 Customer Demo.
