### ISSUE TITLE
Path Detail Page - Android

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#211]
Every path needs to show a page that shows its details (statistics, description, page, milestones etc.) when tapped. Users enroll and follow the paths on this page. Deadline: December 11, 2021 17.00

**Comment by fihlie** [comment]
Backend wasn't read for this deadline however other functionalites were implemented. You can track the progress in 
[235](https://github.com/bounswe/2021SpringGroup11/issues/235)
[236](https://github.com/bounswe/2021SpringGroup11/issues/236)
[237](https://github.com/bounswe/2021SpringGroup11/issues/237)

The issue will be updated when backend connection is completed.

**Comment by fihlie** [comment]
[With this issue](https://github.com/bounswe/2021SpringGroup11/commit/63409233e685c5229652cb1d435ea6668811f8a7) everything completed.  Now you can navigate path page via clicking container and you can use most of the backend properties.
