### ISSUE TITLE
Follow/Unfollow User

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#214]
Follow and unfollow endpoints should be created. They are supposed to return SUCCESS or an Error message. Authentication middleware provides username. Additionally, target username needed.

**Comment by myasins** [comment]
The data of follower and followed users will be kept in another collection in our MongoDB server in order to make the queries easier  to access without being obliged to do array operations.

**Comment by EAltunoglu** [comment]
After postman request screenshot added, this issue can be closed

**Comment by EAltunoglu** [comment]
![3](https://user-images.githubusercontent.com/57532428/145681351-d3772ec1-fd76-4c93-8890-c4693b8f29a0.JPG)
![4](https://user-images.githubusercontent.com/57532428/145681356-63b68653-e441-4c92-b7d0-c1bd97c89747.JPG)

**Comment by EAltunoglu** [comment]
![5](https://user-images.githubusercontent.com/57532428/145681479-914dcd68-478d-40d9-bb51-e1fc7d2b36da.JPG)
![6](https://user-images.githubusercontent.com/57532428/145681481-74a8aec3-08d1-45b0-9816-d5acc6eb4b4f.JPG)
