### ISSUE TITLE
Get Followed Users

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#215]
Get Followed Users endpoint will be created. This endpoint is supposed to return the list of users or an error message. Authentication middleware provides the username. No more field is needed. The MongoDB collection for follower/followed users will be used to get the related data.

**Comment by EAltunoglu** [comment]
Returns two keys. One for following users(key: followers). The other one for followed users(key followed).  Postman request will be added later.

**Comment by EAltunoglu** [comment]
![7](https://user-images.githubusercontent.com/57532428/145681710-56c93b6b-6ac0-40c8-b2b6-a2987549b4ec.JPG)
