### ISSUE TITLE
Follow - Enroll functionalities Implementation

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#226]
Follow and Enroll functionalities of the Path should be implemented after the path page is implemented. 

Please give attention to the requirements while implementing the functionalities. Requirements page:

https://github.com/bounswe/2021SpringGroup11/wiki/Requirements

Some items that can be useful: 
- "Resource: Container for material providing functionality to follow, mark as in progress, mark as finished and comment threads."
- * **1.3.5.** Users *shall* be able to mark any resource, topic or milestone as "in progress", "following" or "done".
    * **1.3.5.1.** The system interface *shall* provide a means of marking and unmarking.
    * **1.3.5.2.** The system interface *shall* display number of users marking each object.
    * **1.3.5.3.** System *shall* denote an association with the user and marked object as any of the above 

Please provide a consistent structure at the end.

Deadline: 11.12.2021 - 20.00

**Comment by bekirtatar** [comment]
Functionalities are added and it works as intended.
