### ISSUE TITLE
Finish Path

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#229]
We reached on a consensus on 'Finish Path' as the name of the endpoint to avoid possible confusions. This endpoint will indicates whether the user finished the contents of the path.

**Comment by SelmanB** [comment]
The relevant commits can be seen in branch 229

**Comment by SelmanB** [comment]
Other teams shall be aware that at the moment the method works for marking the whole path as finished, not individual milestones

**Comment by SelmanB** [comment]
The endpoint was finalized in [this commit]

**Comment by SelmanB** [comment]
Here is an example call from Postman tests:
![Screenshot from 2021-12-11 17-15-05](https://user-images.githubusercontent.com/44111838/145720103-18e92abf-e10d-43a2-a848-8e21add67f1c.png)
