### ISSUE TITLE
Rate Path

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#230]
As we discussed with our team, there is a rating for each path. This endpoint will provide the user to rate a specific path between the predetermined range of values.

**Comment by SelmanB** [comment]
Functionality is implemented in branch 230 and will be reviewed in PR #254 together with #231.

**Comment by SelmanB** [comment]
Example Postman test is here as reference for frontend and Android teams.
![Screenshot from 2021-12-11 17-22-46](https://user-images.githubusercontent.com/44111838/145682673-6d18c344-ba23-4c32-b894-9564567a31ef.png)

**Comment by SelmanB** [comment]
Please note that the rating field can have any numeric value. Its range will be whatever is given from frontend and Android services.
