### ISSUE TITLE
Give an effort for path

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#231]
There is another evaluating point for our paths, it is '**effort'**. This endpoint will provide the user to give a effort point to a specific path between the predetermined range of values.

**Comment by SelmanB** [comment]
The functionality is implemented in branch 231 and will be reviewed in the related PR #254

**Comment by SelmanB** [comment]
The endpoint is tested using Postman and example calls are here for reference:
![Screenshot from 2021-12-11 17-29-36](https://user-images.githubusercontent.com/44111838/145682555-f2999936-f048-46f4-9d65-3af936334f7f.png)

**Comment by SelmanB** [comment]
Said effort can be any numeric value, its allowed values are up to the frontend and Android teams to decide.
