### ISSUE TITLE
Upload updated project plan to Wiki

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#232]
The whole team updated the meeting plan, revising the objectives for 451 Milestone 2, during [Meeting 16.1](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-16.1). The file was edited on @bekirtatar's computer. The latest update (as of writing this) on [that page](https://github.com/bounswe/2021SpringGroup11/wiki/Project-Plan) was done by @meltemarsl  before the customer presentation for 451 Milestone 1. 

The updated plan was added to repo today by @bekirtatar [in this commit](https://github.com/bounswe/2021SpringGroup11/commit/4eaa75fa8fe45c72401540df55bb0ada15e60100#diff-41d311a605520fc7b8b9a980a79437a26e26cebcbfdd569dd78d30f7cb3e7237) today.

Please update the [wiki page](https://github.com/bounswe/2021SpringGroup11/wiki/Project-Plan) with the new project plan.

**Comment by bekirtatar** [comment]
It is uploaded.
