### ISSUE TITLE
Upload the endpoint definitions decided in Meeting 17.1 to Wiki

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#233]
During [Meeting 17.1](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-17.1) we determined almost all the endpoints' inputs, outputs, methods and paths. We did this on the same [codeshare](codeshare.io) document we edited the meeting minutes as far as I can remember. We as the backend team can't find anything about that document in the Wiki. It was @Hazerank's turn to upload the meeting minute that day.

Please upload that crucial endpoint definition document we wrote to the Wiki.

**Comment by Hazerank** [comment]
In the Meeting 17.1 , most of the endpoints' inputs, outputs, methods and paths are decided; however not all the members were in the meeting. So an [issue](#209) created to initiate the review process. After review of all the members, the endpoint should be added to the documentation.
Tl:dr : You can find in this [issue](#209).
