### ISSUE TITLE
Search of Paths

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#243]
Full text index should be created on DB. Definition can be found at #209.

**Comment by myasins** [comment]
![Screen Shot 2021-12-12 at 22 37 22](https://user-images.githubusercontent.com/56367024/145726918-84dbe0f1-26ef-46cf-8224-498b06c1406a.png)

**Comment by myasins** [comment]
Detailed definition of this endpoint will be found [here](https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions).
