### ISSUE TITLE
Favorite Topic

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#244]
An endpoint for adding favourite topic. Definition is not provided for now. It will be added later.

**Comment by SelmanB** [comment]
The functionality is included in branch 244 alongside with other initialization for `topic`. The results are to be reviewed in #252.

**Comment by SelmanB** [comment]
The definition is as follows:

to favorite a topic:
`POST` to `topic/favorite-topic` with JSON body: 
* `username`:string
* `ID`: integer denoting the Wikidata item number for the topic

to remove a topic from favorites:
`POST` to `topic/unfavorite-topic` with JSON body: 
* `username`:string
* `ID`: integer denoting the Wikidata item number for the topic

The response is either string `''SUCCESSFUL"` or an error message `"ALREADY_FAVORITE"` or `"NOT_FAVORITE"`.

**Comment by SelmanB** [comment]
Here are some Postman tests:
![Screenshot from 2021-12-11 17-45-42](https://user-images.githubusercontent.com/44111838/145682471-1cca388e-2869-48f0-9417-3113c1bdbe02.png)
![Screenshot from 2021-12-11 17-46-22](https://user-images.githubusercontent.com/44111838/145682476-369fe164-a344-4f4c-8566-e1b9e1005f56.png)
