### ISSUE TITLE
Android Bug Report on Profiles without Profile Picture 

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#255]
Program gives an error as following when a user with no profile picture uses the application.

![image](https://user-images.githubusercontent.com/36928191/145681330-bda9705a-60b1-436d-b227-1d764caf1111.png)

This error should be handled and profile picture should be the capital of the user's name when there is no profile picture uploaded.

**Comment by kursatbakis** [comment]
OK, so I've figured out the reason. When a user does not have a photo, its 'photo' field becomes empty string, not null. I have changed the if statement that checks the existence of profile photo. Bug is fixed.
