### ISSUE TITLE
Android-Home Page Segmented Control Fav/Unfav Bugfix

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#273]
When user adds a tag to favorites at, for example, popular segment, the tags that are at the same index with this tag also gets added to favorites at other segments.
The same scenario holds for Paths. The items that have no common point except being at the same index should not be dependent to each other.
-Fav a topic at popular segment
-You'll see that at the other 2 segments, topics at same index with the one you fav'ed is also favorited.

**Comment by fihlie** [comment]
In [this branch and PR](https://github.com/bounswe/2021SpringGroup11/pull/292) the bugs are mainly fixed. When backend connection establishes the problem will completely solved.
