### ISSUE TITLE
Creatre Path Input Control Missing

### ISSUE THREAD

**Issue by fihlie** [bounswe/2021SpringGroup11#287]
On create path page, missing inputs can lead severe errors. Please chack and handle the invalid input formats.

Deadline 14.12.2021 14:00

**Comment by Hazerank** [comment]
I will work about It ASAP. Thanks for the notification.

**Comment by Hazerank** [comment]
I have done with the missing controls. Here is corresponding [pull request](https://github.com/bounswe/2021SpringGroup11/pull/289). No problem remains.
