### ISSUE TITLE
Front-end Milestone 4 progress 

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#310]
For the purpose of documentation, can someone from the front-end team report the existing functionalities?

**Comment by meltemarsl** [comment]
* create path
* path, user, topic search
* clickable tags -> directs to clicked tag's page
* related tags & related paths

**Comment by emindeniz99** [comment]
* edit profile
* fav/unfav topic

**Comment by meltemarsl** [comment]
Since the progress is noted, I am closing this issue.
