### ISSUE TITLE
Complete Milestone 2 Report Item3 - Non functional requirements 

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#311]
Could you please review the functional requirements' progress and complete the nonfunctional parts' progress? 
Deadline: 18.12.2021 - 23.00 

# 1. Functional Requirements

## 1.1. Accounts

* **1.1.1.** User *shall* be able to register by providing a valid and verified e-mail address, username, and a strong password. -> Completed.

* **1.1.2.** User *shall* be able to login by providing verified e-mail address. -> Completed. 

* **1.1.3.** The user *shall* be able to delete their accounts. -> Not started

* **1.1.4.** The user *shall* be able to reset its password via providing its e-mail address and via passing a challenge-response test such as "captcha" . -> In progress

    * **1.1.4.1.** In this case, System *should* send a mail for resetting password. In order for resetting to happen, user should initiate resetting process from the e-mail that is specifically sent from the system. -> In progress

* **1.1.5.** System *shall* include admin privileged user whose privileges are as follows: -> Not implemented.
   * **1.1.5.1** An admin privileged user *should* be ban or permanently delete users -> Not implemented.
   * **1.1.5.2** An admin privileged user *should* be remove comments, materials and resources. -> Not implemented.
   * **1.1.5.3** An admin privileged user *should* be able to give admin privileges to a normal user while declaring it as another admin.  -> Not implemented.

* **1.1.6.** Every user *shall* have a unique and non-alterable username called user identifier which will *shall* be determined at the creation of the account. -> In progress.
   * **1.1.6.1.** System *shall* not allow new accounts to use an user identifier associated with a deleted account, or that is not associated with any account anymore for any reason. -> In progress.  

## 1.2. Self-Development

* **1.2.1.** User *shall* create a resource which includes a description, image and materials. The details of resource is explained in the glossary.  -> Completed.

* **1.2.2.** The System *shall* reliably record any progress data supplied by the users grouped by materials and topics. -> Not implemented.
    * **1.2.2.1.** The System *should* display at least one central statistic of this information grouped by materials and topics. -> Not implemented.
    * **1.2.2.2.** The System *should* display progress data associated by a user to the users associated with that user. -> Not implemented.

* **1.2.3.** The System *should* provide the user with a graphical overview of their past effort. There *should* be a page to show this information to the user. -> In progress.

* **1.2.4.** The System *shall* determine and inform its users about topics they could be potentially interested. -> Completed.
    * **1.2.4.1.** The System Interface *shall* provide a page that the users can intentionally navigate to and see this information that may also contain other functionality. -> Completed.

* **1.2.5.** The System *shall* supply its users with recommendation of resources. -> In Progress
    * **1.2.5.1.** The System Interface *shall* provide a page that the users can intentionally navigate to and see this information that may also contain other functionality. -> In Progress

* **1.2.6.** The System *should* offer a means of reliably proving realized effort and any accomplishment of a user to any third party authorized by that user. -> Not implemented

* **1.2.7.** The users *shall* be able to reliably record and edit some objectives they determine as a set of material-deadline pairs. -> In progress
    
* **1.2.8.** The users *should* be able to record topics they want to improve on, or break/develop a habit. -> In progress.

* **1.2.9.** The users *shall* be able to work on their determined objectives as a group. -> Not implemented.
    * **1.2.9.2.** Users *should* be able to create groups under collective resources that can be only visible to users that are invited to this group. -> Not implemented
       

## 1.3. Social Interaction

* **1.3.1.** The users *should* have profile pages, and be able to modify their profiles. -> Completed.
* **1.3.2.** The users *should* be able to share their accomplishments and preferred topics via other applications. -> Not implemented

* **1.3.3.** The users *should* be able to share their comments on specific topics or resources. -> Not implemented
    * **1.3.3.1.** Any comment *shall* display user identifier of the user that posted that comment -> Not implemented
         * **1.3.3.1.1.** If a user account is deleted, user identifier associated with a comment *shall* become "deleted user". -> Not implemented
    * **1.3.3.2.** A comment *should* be able to have a comment list associated with it, which *should* have nested aligning with respect to the owning comment. -> Not implemented
 
    * **1.3.3.3.** Any user *shall* have the option to delete any comment posted by that user. -> Not implemented
        *  **1.3.3.3.1.** If a comment is deleted by the posting user and there exists a nonempty comment list associated with it, then the Interface *shall* display the deleted parent comment as the message "deleted comment". -> Not implemented
    * **1.3.3.4.** A comment *should* have a ballot associated with it which shows rate of the comment. Detailed ballot description is done at the glossary.  -> Not implemented

* **1.3.4.** The users *should* be able to search for other users via topics that is associated with them or via username. -> In progress

* **1.3.5.** Users *shall* be able to mark any resource, topic or milestone as "in progress", "following" or "done". -> In progress
    * **1.3.5.1.** The system interface *shall* provide a means of marking and unmarking. -> Completed.
    * **1.3.5.2.** The system interface *shall* display number of users marking each object. -> Not implemented.
    * **1.3.5.3.** System *shall* denote an association with the user and marked object as any of the above -> Completed.

* **1.3.7.** System *should* include two ballots denoting "effort" and "rating" associated with every resource. -> Completed.

## 1.4. User Experience

* **1.4.1.** The System interface *should* give its users notification messages. -> Not implemented.
    * **1.4.1.1.** If implemented, those notifications *shall* be given for scheduled resource milestones reminding the deadlines.  -> Not implemented.

* **1.4.2.** The users *should* be able to customize the way the notifications are sent. -> Not implemented.

* **1.4.3.** The users *should* be able to search data assigned to topics using strings. -> Completed.

* **1.4.4.** The users *should* be able to access other users' profiles. -> Completed.
    * **1.4.4.1.** The System Interface *should* display user's associations with topics, resources and milestones in the profile. -> Completed.

# 2. Non-Functional Requirements

## 2.1. Availability
* **2.1.1.** An Android Application and a Web Application *shall* be implemented as instances of the Interface.
    * **2.1.1.1.** Android operating systems of version 10 and above *shall* be supported.

* **2.1.2.** The Interface *shall not* require any user to give text commands for any of its functionalities. It *shall* be possible to give all commands through the interface using a graphical interface.
    * *2.2.2.1.* Those commands *should* be either the standard input types provided by HTML 5 standard or those with equivalent functionality.

* **2.1.3.** The System *shall* express topics using semantic representation as defined in [Wikidata](https://www.wikidata.org/).
    * **2.1.3.1.** Topics *shall* be indexed using both the integer semantic ID as indexed in [Wikidata](https://www.wikidata.org/) in the Infrastructure.
    * **2.1.3.2.** The Interface *should* represent the topics as strings in the preferred language of the operating system of the user and a representation in whatever language is available if it is not available.
        * **2.1.3.2.1.** If the representation of the user's language is not found and there are multiple languages for which a representation is available, English *shall* be prioritized.

* **2.1.4.** The Web Application *should* only use standard HTML5 and Javacscript code that is compatible with Chromium and Firefox .

## 2.2. Performance
* **2.2.1.** The Infrastructure *shall* be able to support at least 100 user actions per second.

* **2.2.2.** The Infrastructure *shall* be able to support at least 10000 accounts.

* **2.2.3.** The Infrastructure *shall* have a response time of less than 1.0 second excluding network delay.

* **2.2.4.** The Infrastructure *shall* have an uptime of at least 99%.

## 2.3. Privacy

* **2.3.1.** The System *shall* be compliant with [GDPR](https://gdpr.eu/).
    * **2.3.1.1.** Users *shall* be given explicit and concise explanation of how their data may be used.
    * **2.3.1.2.** The interface *shall* give the users a means of approving that they understood how their data may be used at the time of account creation.
    * **2.3.1.3.** If any change of how data may be used, all users *shall* be given a notice and prohibited from using the System until they approve it.

* **2.3.2.** Users *shall* have authority over visibility by third entities of data related to their accounts. 
    * **2.3.2.1.** The interface *should* provide a simple page in which the users can select this.

## 2.4. Security

* **2.4.1.** Data that shall be reliably recorded in the Infrastructure *should* be recorded using a means of redundancy, such as using RAID.

* **2.4.2.** Application layer protocol used by The System *shall* be restricted to HTTPS.

 * **2.4.3** Passwords *shall* be hashed before being stored and verified using a NIST-approved cryptographically secure hash function using a salt that depends on the exact user and a system-wide nonce acquired from a reliable entropy source.

**Comment by bekirtatar** [comment]
The progress that you documented in the milestone report matches our project. I added the non-functional requirement progress to the milestone report.

**Comment by bekirtatar** [comment]
### 2. Non-Functional Requirements

#### 2.1. Availability
* **2.1.1.** An Android Application and a Web Application *shall* be implemented as instances of the Interface. -> Completed.
    * **2.1.1.1.** Android operating systems of version 10 and above *shall* be supported. -> Completed.

* **2.1.2.** The Interface *shall not* require any user to give text commands for any of its functionalities. It *shall* be possible to give all commands through the interface using a graphical interface. -> Completed.
    * *2.2.2.1.* Those commands *should* be either the standard input types provided by HTML 5 standard or those with equivalent functionality. -> Completed.

* **2.1.3.** The System *shall* express topics using semantic representation as defined in [Wikidata](https://www.wikidata.org/). -> Completed.
    * **2.1.3.1.** Topics *shall* be indexed using both the integer semantic ID as indexed in [Wikidata](https://www.wikidata.org/) in the Infrastructure. -> Completed.
    * **2.1.3.2.** The Interface *should* represent the topics as strings in the preferred language of the operating system of the user and a representation in whatever language is available if it is not available. -> Not implemented.
        * **2.1.3.2.1.** If the representation of the user's language is not found and there are multiple languages for which a representation is available, English *shall* be prioritized. -> Not implemented.

* **2.1.4.** The Web Application *should* only use standard HTML5 and Javacscript code that is compatible with Chromium and Firefox. -> Completed.

#### 2.2. Performance
* **2.2.1.** The Infrastructure *shall* be able to support at least 100 user actions per second. -> In progress.

* **2.2.2.** The Infrastructure *shall* be able to support at least 10000 accounts. -> In progress.

* **2.2.3.** The Infrastructure *shall* have a response time of less than 1.0 second excluding network delay. -> In progress.

* **2.2.4.** The Infrastructure *shall* have an uptime of at least 99%. -> In progress.


#### 2.3. Privacy

* **2.3.1.** The System *shall* be compliant with [GDPR](https://gdpr.eu/). -> Not implemented.
    * **2.3.1.1.** Users *shall* be given explicit and concise explanation of how their data may be used. -> Not implemented.
    * **2.3.1.2.** The interface *shall* give the users a means of approving that they understood how their data may be used at the time of account creation. -> Not implemented.
    * **2.3.1.3.** If any change of how data may be used, all users *shall* be given a notice and prohibited from using the System until they approve it. -> Not implemented.


* **2.3.2.** Users *shall* have authority over visibility by third entities of data related to their accounts. -> Not implemented.
    * **2.3.2.1.** The interface *should* provide a simple page in which the users can select this. -> Not implemented.

#### 2.4. Security

* **2.4.1.** Data that shall be reliably recorded in the Infrastructure *should* be recorded using a means of redundancy, such as using RAID. -> Not implemented.

* **2.4.2.** Application layer protocol used by The System *shall* be restricted to HTTPS. -> Not implemented.

 * **2.4.3** Passwords *shall* be hashed before being stored and verified using a NIST-approved cryptographically secure hash function using a salt that depends on the exact user and a system-wide nonce acquired from a reliable entropy source. -> Not implemented.

**Comment by bekirtatar** [comment]
The report is completed and delivered. Since no further change is required, I am closing this issue.
