### ISSUE TITLE
Milestone 4 Group Report Review

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#312]
File is attached. Please review and report issues.

[draft2Customer Demo 2 Milestone.pdf](https://github.com/bounswe/2021SpringGroup11/files/7739906/draft2Customer.Demo.2.Milestone.pdf)

**Comment by meltemarsl** [comment]
There is a mistake about title lines. Could you please join the second line with the first line

**Comment by emindeniz99** [comment]
Thank you, the issue is fixed. 
https://github.com/bounswe/2021SpringGroup11/blob/master/451-deliverables/M2-Group11.pdf
