### ISSUE TITLE
Get Following Users and Get Followers

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#313]
What is the get-follow API endpoint?
And Get Following Users and Get Followers API endpoints are necessary for frontend.
It should return username and profile photo.
The following and followers are shown on profile page with a popup.
![image](https://user-images.githubusercontent.com/44745432/147364427-2df3ebeb-8cd8-4253-b231-916747ae6067.png)
![image](https://user-images.githubusercontent.com/44745432/147364526-cc5a286d-85b5-4b5a-a2f6-77a38954d082.png)

**Comment by myasins** [comment]
Related information is provided in [API Endpoint Definitions](https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions#get-follower-and-followed-usersuserget-follow-get). And a request example is provided [here](https://github.com/bounswe/2021SpringGroup11/issues/215).
