### ISSUE TITLE
Upload Android meeting report on 27.12.2021

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#314]
The android team has come together and decided on the tasks that should be completed until next week. Every member is assigned several tasks. Hazar kept the report of this meeting.

**Comment by Hazerank** [comment]
Hi Kürşat,
Corresponding meeting report is cleared and uploaded to our repo. You can find the report [here](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.Android.2).
