### ISSUE TITLE
Frontend Develop-Master merge problem

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#315]
The Master branch is merged into the frontend/develop by @emindeniz99. This merge caused a build error in our develop branch and deployment. Reverting the last commit will fix this problem.

Assignee: @meltemarsl 
Deadline: 28.12.2021 - 20.00

**Comment by meltemarsl** [comment]
The last commit is reverted. After that, I also checked the Renaissance application. It was working, the problem is fixed.

<img width="796" alt="revert" src="https://user-images.githubusercontent.com/44238703/147661339-7a524fa4-a2b1-4c7a-b255-5d49a89b5283.png">
