### ISSUE TITLE
Create Path Endpoint Update

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#317]
It is decided to change the general structure of the path in the last meeting [(Meeting 21.1 - 28.12.2021 )](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-21.1). As discussed in the meeting, we decided to implement tasks and milestones in a learning path. Following this decision, it is said that milestones and tasks will be differentiate via an id.

What is the id structure in the backend team's plans, more specifically, will it be an integer field like "0 for task, 1 for milestone" or a string field like " Task for tasks and Milestone for milestones"?

**Comment by EAltunoglu** [comment]
Done in #325.
