### ISSUE TITLE
Create Issues for Milestone 5 features

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#319]
* Activity Stream - [relevant standard](https://www.w3.org/TR/activitystreams-core/)
    * [x] #320
    * [x] #321
    * [x] #322
    * [x] #323
    * [x] #326
        * The past endpoints that need this are marked [here](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021) 
 * Updated Path Hierarchy - [relevant meeting note](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-21.1])
     * [x] #324
     * [x] #325
     * [x] #327
 * Resource
     * [x] #328
     * [x] #329
 * It should be kept in mind that the issue #142 is active and should be considered while implementing those above.

**Comment by EAltunoglu** [comment]
activity-streams label created to use in issues.

**Comment by SelmanB** [comment]
All issues are created and fulfilled. This issue can be closed now.
