### ISSUE TITLE
Research on JSON-LD Activity Stream standard and write a template

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#320]
Our results on activity stream endpoints requested in issues #322 and #323 should rely on the standard specified [here](https://www.w3.org/TR/activitystreams-core/). It should be researched by all backend team members.

Furthermore, the way we store activity information as requested in issue #321 and #326 should take into account the ease at which the data can be converted into this standard. To make this process much easier, a template for JSON-LD structures of _Activity Streams 2.0_ should be created

**Comment by myasins** [comment]
We researched and discussed the way we will implement according to standards with @SelmanB and @EAltunoglu . We decided to follow the examples [here](https://www.w3.org/TR/activitystreams-core/#activities).
