### ISSUE TITLE
Write a MongoDB model for JSON-LD Actvity Stream

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#321]
A model that stores the events logged by the functionality specified in #326 is necessary. It should comply with the finding from #320 to make implementation of #322 and #323 easier.

**Comment by EAltunoglu** [comment]
// PATH CREATE
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "{username} created a path {PATH_NAME}",
    "type": "Create",
    "actor": {
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "id": "{frontend path link}",
        "type": "Document",
        "name": "{path name}"
    }
}

// PATH ENROLL
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Eren enrolled to {PATH_NAME}",
    "type": "Join",
    "actor": {
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "id": "{frontend path link}",
        "type": "Document",
        "name": "{path name}"
    }
}

// PATH FOLLOW
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Eren followed {PATH_NAME}",
    "type": "Follow",
    "actor": {
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "id": "{frontend path link}",
        "type": "Document",
        "name": "{path name}"
    }
}

// TASK FINISH
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Eren finished a task {task_name}",
    "type": "Create",
    "actor": {
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "type": "Event",
        "name": "{task name} finished",
        "attributedTo": {
            "id": "{frontend path link}",
            "type": "Document",
            "name": "{path name}"
          },
    }
}

// TOPIC FOLLOW
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Eren followed a topic {topic_name}",
    "type": "Follow",
    "actor": {
 //       "id": "{frontend user link}",
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "type": "Document",
        "name": "{topic_name}",
    }
}

// USER FOLLOW
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Eren followed a user {username}",
    "type": "Follow",
    "actor": {
        "type": "Person",
        "name": "{username}"
    },
    "object": {
        "type": "Person",
        "name": "{username}",
    }
}

// hepsine published eklencek

**Comment by SelmanB** [comment]
See [this file](https://github.com/bounswe/2021SpringGroup11/blob/326/source/backend/api/common/activitystreams.py) for the implementation. All other code reading from or writing into the `activitystreams` collection is supposed to use that interface for correct formatting.
