### ISSUE TITLE
Create Task MongoDB Model

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#324]
We will add a 'type' attribute for milestone model we used in our project. This 'type' attribute will specify that whether the point is a task or a milestone. We decided to implement in this way because we will use the same structures in both milestone and task models. This decision is made in this [meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.1---21.12.2021).

**Comment by EAltunoglu** [comment]
Feature implemented in branch 327.
