### ISSUE TITLE
Include Activity Stream loggers for some past endpoints and the finish task endpoint

### ISSUE THREAD

**Issue by EAltunoglu** [bounswe/2021SpringGroup11#326]
We have prioritized some of the endpoints in the Additional Notes of [Meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021).
Research and creating models will be done under #320 and #321.
First, we will implement these endpoints.

- [x] #342
- [x] #343
- [x] #344
- [x] #346
- [x] #347
- [x] #348

After Implementing these endpoints. Some other endpoints can be updated for Activity Streams.

- [x] #345
- [x] #349

**Comment by meltemarsl** [comment]
> We have prioritized some of the endpoints in the Additional Notes of [Meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021). Research and creating models will be done under #320 and #321. First, we will implement these endpoints.
> 
> * [ ]  Create Path (`create-path`) Endpoint Activity Stream Update
> * [ ]  Follow Path (`follow-path`) Endpoint Activity Stream Update
> * [ ]  Enroll Path (`enroll-path`) Endpoint Activity Stream Update
> * [ ]  Finish Path (`finish-path`) Endpoint Activity Stream Update
> * [ ]  Finish Milestone (`finish-milestone`) Endpoint Activity Stream Update
> * [ ]  Finish Task (`finish-task`) Endpoint Activity Stream Update
> * [ ]  Follow User (`follow-user`) Endpoint Activity Stream Update
> 
> After Implementing these endpoints. Some other endpoints can be updated for Activity Streams.

Could you please add also the Fav Topic (`fav-topic`) and Unfav Topic (`unfav-topic`) functionalities to the activity stream

**Comment by SelmanB** [comment]
Please mind this detail and make any corrections if necessary on branch 326 before closing this issue:

- [ ] Double-Check the Activity Streams Action Types for Conformity

**Comment by SelmanB** [comment]
Finishtask being waited above is to be merged in #358

**Comment by SelmanB** [comment]
> > We have prioritized some of the endpoints in the Additional Notes of [Meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021). Research and creating models will be done under #320 and #321. First, we will implement these endpoints.
> > 
> > * [ ]   Create Path (`create-path`) Endpoint Activity Stream Update
> > * [ ]   Follow Path (`follow-path`) Endpoint Activity Stream Update
> > * [ ]   Enroll Path (`enroll-path`) Endpoint Activity Stream Update
> > * [ ]   Finish Path (`finish-path`) Endpoint Activity Stream Update
> > * [ ]   Finish Milestone (`finish-milestone`) Endpoint Activity Stream Update
> > * [ ]   Finish Task (`finish-task`) Endpoint Activity Stream Update
> > * [ ]   Follow User (`follow-user`) Endpoint Activity Stream Update
> > 
> > After Implementing these endpoints. Some other endpoints can be updated for Activity Streams.
> 
> Could you please add also the Fav Topic (`fav-topic`) and Unfav Topic (`unfav-topic`) functionalities to the activity stream

typo in #347 is corrected to `favorite-topic` and the feature requested is implemented there and merged into the branch of this issue (namesake 326).

**Comment by SelmanB** [comment]
Only remaining `activitystreams` features (`finish-task`, `finish-milestone`) require the branch 326 (including merged activitystreams functionality) into 142, which contains those two endpoints merged from other branches.

**Comment by SelmanB** [comment]
The endpoints are tested and are in working condition. Individual issues are closed and the feature branch for this issue is merged. The issue can be closed
