### ISSUE TITLE
Create Resource Endpoint & Model

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#328]
It will be added a new 'Resource' model in our project. 'Resource's will be connected to tasks, which we introduced in #324. Additionally, resource will include links and information related to the task it is connected.

**Comment by EAltunoglu** [comment]
![1](https://user-images.githubusercontent.com/57532428/147885748-2e490017-5a97-455b-a44b-2c7b1569ee8d.JPG)
Unit tests are provided for the endpoint.

**Comment by EAltunoglu** [comment]
Feature is deployed.
