### ISSUE TITLE
Update `get-path` endpoint to include "task"s

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#329]
An endpoint to get information about paths was created in #267. However, the internal structure is changed according to the related [customer meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-20.2---24.12.2021) in #324 (novel items are closely related with #325). Now the `get-path` endpoint must be modified to include the new information specified.

This is going to necessitate updating the unit tests for that endpoint tracked in #142.

**Comment by EAltunoglu** [comment]
Since using milestone model for task, there is no need for updating `get-path`.
