### ISSUE TITLE
Transfer our web application to the CRA

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#330]
We are currently using parcel as a bundler but we are getting so many errors with it. We need to transfer our code to the create react app template and we need to use webpack as a bundler.

Deadline: 20:00 02/01/2021

**Comment by meltemarsl** [comment]
Renaissance was transferred to the CRA. 

Related action: https://github.com/bounswe/2021SpringGroup11/actions/runs/1645654577

<img width="825" alt="ssss" src="https://user-images.githubusercontent.com/44238703/147874735-98ac0211-6592-4e74-93b1-f58e2c35e257.png">
