### ISSUE TITLE
Update add path functionality in the web application.

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#332]
The path structure will be updated according to the group discussions in the [meeting](https://github.com/bounswe/2021SpringGroup11/wiki/Meeting-21.1).

**Comment by bekirtatar** [comment]
@Hazerank, Could you share android design pictures in this issue?

**Comment by Hazerank** [comment]
Hi Bekir, the design is still in development. However, here is the current status of create Path page.
<img width="467" alt="Screen Shot 2022-01-02 at 14 46 53" src="https://user-images.githubusercontent.com/36928191/147874783-d181eab2-204e-41c0-bc6a-a2ab012c079a.png">
<img width="467" alt="Screen Shot 2022-01-02 at 14 47 15" src="https://user-images.githubusercontent.com/36928191/147874784-61d125b6-6a79-4b19-95e7-f63d23d8bbac.png">
<img width="467" alt="Screen Shot 2022-01-02 at 14 47 35" src="https://user-images.githubusercontent.com/36928191/147874786-0bf29d77-14c0-4658-958e-d7121b5977f9.png">
