### ISSUE TITLE
Update Get Enrolled Paths and Get Favorite Paths Endpoints

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#333]
In the user profile page, android app is supposed to display a list of user's enrolled and favorite paths. Backend only returns the list of _id's from the endpoints. For us to display these items, we need basic properties such as name, photo, effort, rating, isFav to these paths. Endpoints need to be updated.

**Comment by EAltunoglu** [comment]
In `/path/get-enrolled-paths/` `/path/get-followed-paths/`, response body have needed properties.
