### ISSUE TITLE
Endpoints for Home Page: Popular, For You, New

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#334]
Home Page displays lists of Topics (tags) and Learning paths. 
All seperate endpoints for popular, for you and new. Backend team can decide on the logic for them.
Each endpoint should be in this structure:
```
{
  "tags": [
    {
    name, ID and isFav
    },
    {
    name, ID and isFav
    }
  ],
  "paths": [
    {
    photo, name, rating, effort, isFav, ID 
    }, 
    {
    photo, name, rating, effort, isFav, ID
    }
  ]
}
```

**Comment by EAltunoglu** [comment]
![pop](https://user-images.githubusercontent.com/57532428/147984056-92c7b1a8-b6b7-4ead-b03b-d2ab588ec376.JPG)
![foryou](https://user-images.githubusercontent.com/57532428/147984147-85f1e89c-0093-4f67-be52-91cffb9bb27b.JPG)
![new](https://user-images.githubusercontent.com/57532428/147984156-27dfbe8d-5e28-46f0-be51-039d4640da2d.JPG)

**Comment by EAltunoglu** [comment]
It is implemented and reviewed. Unit test are also provided. Mobile&Frontend teams will be informed when it is deployed.
