### ISSUE TITLE
Add new details to get-profile endpoint

### ISSUE THREAD

**Issue by kursatbakis** [bounswe/2021SpringGroup11#335]
In addition to finishedResourceCount, the NUMBER OF followings and followers is required. Also, if the related system exists, user's title should return. Possible titles are, in order:
-Beginner
-Specialist
-Expert
-Master
-Grandmaster
If title feature is not going to be implemented, frontend and mobile needs to remove it from the user interface. Let us know.

**Comment by EAltunoglu** [comment]
Title feature is not going to be implemented. Frontend&Mobile teams will be informed when get-profile endpoint updated.

**Comment by EAltunoglu** [comment]
![profile](https://user-images.githubusercontent.com/57532428/147986465-740b3c80-2596-44ef-98f2-12988901cc00.JPG)
