### ISSUE TITLE
Search Topic Endpoint Bug Report

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#338]
It is encountered an unexpected result in the Search Topic endpoint. For some queries, instead of returning empty list, endpoint returns a "KeyError". Bug details are specified below:

- Query: 
http://35.209.23.51/topic/search-topic/motor-car
- Expected Result:
[ ] or Topic about motor car
- Encountered Result:
KeyError at /topic/search-topic/motor-car/    -- 'description'
Screenshot of Postman page:
<img width="1005" alt="Screen Shot 2022-01-02 at 17 26 47" src="https://user-images.githubusercontent.com/36928191/147879021-fd5f6e15-a519-41ef-8282-3bd58f2364a5.png">

**Comment by EAltunoglu** [comment]
It was a minor bug, handled in #341. Frontend&Mobile teams will be informed when it is deployed.

**Comment by EAltunoglu** [comment]
Bugfix is deployed.
