### ISSUE TITLE
Profile page Follow-Unfollow button

### ISSUE THREAD

**Issue by meltemarsl** [bounswe/2021SpringGroup11#374]
The un/follow button on the profile page should be colored. 

The closed pull request related to this: https://github.com/bounswe/2021SpringGroup11/pull/372

Deadline: 03.01.2022 - 19.00

**Comment by emindeniz99** [comment]
![image](https://user-images.githubusercontent.com/44745432/147934317-4cad2f31-1c72-410c-9f7b-951c2be764bc.png)
![image](https://user-images.githubusercontent.com/44745432/147934347-eee9ea3c-c1d7-4025-aa02-4aad9f5ff8da.png)
