### ISSUE TITLE
Search-Path Endpoint Update Request

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#386]
It is seen that in the implementation of Search-Path endpoint, some of the  fields are missing as :
- Rating
- Effort

As in  #209, search-path endpoint should have included those features but as one can see in #243, the search-path is not contains rating and effort. 
In order to implement search feature in mobile, those data is critical and should be included.

**Comment by myasins** [comment]
Updated
![Screen Shot 2022-01-03 at 21 51 06](https://user-images.githubusercontent.com/56367024/147968058-7b98f84c-b4ac-4bf5-9df3-3bda83023ea4.png)
