### ISSUE TITLE
Implementing navigation to results

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#397]
Reaching the results is one half of the intended implementation. Users should be able to navigate to the result. So for each type of result, navigation policy should be implemented.

**Comment by Hazerank** [comment]
I have done the connection between path containers and the path pages. ( Regarding commit f079e9f1982d52df116a6c664bc20778c331cbc8). For the other two's, my two other colleagues will implement them. To be specific:
- @kursatbakis will implement connection between profile page and profile containers.
- @fihlie will implement connection between topic page and topic containers.

**Comment by kursatbakis** [comment]
I've completed the navigation to profile page.

**Comment by fihlie** [comment]
Topic page one of the latest features for mobile. I've implemented the topic page so I've established connections between them.
