### ISSUE TITLE
Prepare a personal report structure to submit weekly

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/2021SpringGroup11#4]
It should include a time table for work done for each member and explanation. 

* do not forget to add your link to the sidebar

- [x] FİKRİ
- [x] ŞULE
- [ ] EGEMEN
- [x] EMİN
- [x] BEKİR
- [x] EREN
- [x] CANBERK
- [x] SELMAN BERK
- [x] MEHMET YASİN

**Comment by emindeniz99** [comment]
StackEdit – In-browser Markdown editor https://stackedit.io/
