### ISSUE TITLE
Learn Django, Postgresql, docker

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/2021SpringGroup11#42]
Go over the tutorials again, ps, example repos, our repo
download, deploy, create instances, follow the tutorials,

use your knowledge on the CryptoGraph API that I will create.

**Comment by SelmanB** [comment]
*Discussion migrated from Slack:*
@SelmanB : @emindeniz99 is it sufficient (for docker) if we just go over [this tutorial](https://docs.docker.com/samples/django/) what are the files we should be relasing after doing the same?

@emindeniz99 : That will be enough.

@SelmanB : Thanks
