### ISSUE TITLE
Create an API on Crypto/Crypto parities

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/2021SpringGroup11#43]
from FinnHub choose 5 parities,
create an API using this API, a DB to store data to draw a graph to show on frontend for the user.

**Comment by canberkboun9** [comment]
Could not successfully create the api because django gives errors for hours, could not get help as all the team members always busy.

**Comment by canberkboun9** [comment]
could not resolve the dotenv installing problem

**Comment by myasins** [comment]
no more on our agenda
