### ISSUE TITLE
Review the code of other team members

### ISSUE THREAD

**Issue by myasins** [bounswe/2021SpringGroup11#67]
Everyone must review the code of the others up to the end of the submission deadline. 
Close the pull requests after completing this.
Anybody completed this process must mark there.

After everybody is done, this issue will be closed.
- [x] FİKRİ
- [x] EMİN
- [x] BEKİR
- [x] EREN
- [ ] CANBERK
- [x] SELMAN BERK
- [x] MEHMET YASİN

**Comment by emindeniz99** [comment]
I have reviewed this PR "stocksAPI added #52"
