### ISSUE TITLE
Creating Personal Wiki Pages for New Members

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#90]
Welcome to our team, Hazar Meltem and Kürşat. 

Can you create your personal wiki pages? You can tell about yourselves shortly and add some links to your personal GitHub, LinkedIn vs. pages. Your contact information also will be a nice detail to see on your personal pages. You should also add a link that directs to your personal page into README.md file and group members section at our project wiki.

Sub-issues
- [x] #102
- [x] Create Personal Wiki Page - Meltem (New Member) 
- [x] #107

**Comment by emindeniz99** [comment]
> Thanks Bekir! I have created my personal wiki page draft and added required links to the README.md and group members section at wiki.

Could you open a new issue for your task?

- [ ] Create Personal Wiki Page - Hazar (New Member)

**Comment by meltemarsl** [comment]
I created my personal wiki page. Since Kürşat and Hazar have already been created, I am closing the issue.
